// This file is auto-generated by @hey-api/openapi-ts


export enum DirectionModelEnum {
    ASCENDING = 'Ascending',
    DESCENDING = 'Descending'
}

export enum EventMessageTypeModelEnum {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export enum ResourceGroupTypeEnum {
    IMAGES = 'Images',
    SCRIPTS = 'Scripts',
    LINKS = 'Links',
    CSS = 'Css',
    OTHER = 'Other'
}