// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAverageDataData, GetAverageDataErrors, GetAverageDataResponses, GetCheckPageData, GetCheckPageErrors, GetCheckPageResponses, GetOverviewDataData, GetOverviewDataErrors, GetOverviewDataResponses, GetPageDataData, GetPageDataErrors, GetPageDataResponses, PostSavePageDataData, PostSavePageDataErrors, PostSavePageDataResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class SustainabilityService {
    public static getCheckPage<ThrowOnError extends boolean = true>(options?: Options<GetCheckPageData, ThrowOnError>): RequestResult<GetCheckPageResponses, GetCheckPageErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetCheckPageResponses, GetCheckPageErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/sustainability/api/v1/checkPage',
            ...options
        });
    }
    
    public static getAverageData<ThrowOnError extends boolean = true>(options?: Options<GetAverageDataData, ThrowOnError>): RequestResult<GetAverageDataResponses, GetAverageDataErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetAverageDataResponses, GetAverageDataErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/sustainability/api/v1/getAverageData',
            ...options
        });
    }
    
    public static getOverviewData<ThrowOnError extends boolean = true>(options?: Options<GetOverviewDataData, ThrowOnError>): RequestResult<GetOverviewDataResponses, GetOverviewDataErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetOverviewDataResponses, GetOverviewDataErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/sustainability/api/v1/getOverviewData',
            ...options
        });
    }
    
    public static getPageData<ThrowOnError extends boolean = true>(options?: Options<GetPageDataData, ThrowOnError>): RequestResult<GetPageDataResponses, GetPageDataErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetPageDataResponses, GetPageDataErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/sustainability/api/v1/getPageData',
            ...options
        });
    }
    
    public static postSavePageData<ThrowOnError extends boolean = true>(options: Options<PostSavePageDataData, ThrowOnError>): RequestResult<PostSavePageDataResponses, PostSavePageDataErrors, ThrowOnError> {
        return (options.client ?? client).post<PostSavePageDataResponses, PostSavePageDataErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/sustainability/api/v1/savePageData',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
