// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CheckPageData, CheckPageResponses, GetAverageDataData, GetAverageDataResponses, GetOverviewDataData, GetOverviewDataResponses, GetPageDataData, GetPageDataResponses, IsSiteCheckRunningData, IsSiteCheckRunningResponses, SavePageDataData, SavePageDataResponses, StartSiteCheckData, StartSiteCheckResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class SustainabilityService {
    public static checkPage<ThrowOnError extends boolean = true>(options?: Options<CheckPageData, ThrowOnError>) {
        return (options?.client ?? client).get<CheckPageResponses, unknown, ThrowOnError>({
            url: '/umbraco/sustainability/api/v1/checkPage',
            ...options
        });
    }
    
    public static getAverageData<ThrowOnError extends boolean = true>(options?: Options<GetAverageDataData, ThrowOnError>) {
        return (options?.client ?? client).get<GetAverageDataResponses, unknown, ThrowOnError>({
            url: '/umbraco/sustainability/api/v1/getAverageData',
            ...options
        });
    }
    
    public static getOverviewData<ThrowOnError extends boolean = true>(options?: Options<GetOverviewDataData, ThrowOnError>) {
        return (options?.client ?? client).get<GetOverviewDataResponses, unknown, ThrowOnError>({
            url: '/umbraco/sustainability/api/v1/getOverviewData',
            ...options
        });
    }
    
    public static getPageData<ThrowOnError extends boolean = true>(options?: Options<GetPageDataData, ThrowOnError>) {
        return (options?.client ?? client).get<GetPageDataResponses, unknown, ThrowOnError>({
            url: '/umbraco/sustainability/api/v1/getPageData',
            ...options
        });
    }
    
    public static isSiteCheckRunning<ThrowOnError extends boolean = true>(options?: Options<IsSiteCheckRunningData, ThrowOnError>) {
        return (options?.client ?? client).get<IsSiteCheckRunningResponses, unknown, ThrowOnError>({
            url: '/umbraco/sustainability/api/v1/isSiteCheckRunning',
            ...options
        });
    }
    
    public static savePageData<ThrowOnError extends boolean = true>(options?: Options<SavePageDataData, ThrowOnError>) {
        return (options?.client ?? client).post<SavePageDataResponses, unknown, ThrowOnError>({
            url: '/umbraco/sustainability/api/v1/savePageData',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static startSiteCheck<ThrowOnError extends boolean = true>(options?: Options<StartSiteCheckData, ThrowOnError>) {
        return (options?.client ?? client).sse.get<StartSiteCheckResponses, unknown, ThrowOnError>({
            url: '/umbraco/sustainability/api/v1/startSiteCheck',
            ...options
        });
    }
}
