// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { CheckPageData, CheckPageResponse, GetAverageDataData, GetAverageDataResponse, GetOverviewDataData, GetOverviewDataResponse, GetPageDataData, GetPageDataResponse, SavePageDataData, SavePageDataResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class SustainabilityService {
    public static checkPage<ThrowOnError extends boolean = true>(options?: Options<CheckPageData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<CheckPageResponse, unknown, ThrowOnError>({
            url: '/umbraco/sustainability/api/v1/checkPage',
            ...options
        });
    }
    
    public static getAverageData<ThrowOnError extends boolean = true>(options?: Options<GetAverageDataData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetAverageDataResponse, unknown, ThrowOnError>({
            url: '/umbraco/sustainability/api/v1/getAverageData',
            ...options
        });
    }
    
    public static getOverviewData<ThrowOnError extends boolean = true>(options?: Options<GetOverviewDataData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetOverviewDataResponse, unknown, ThrowOnError>({
            url: '/umbraco/sustainability/api/v1/getOverviewData',
            ...options
        });
    }
    
    public static getPageData<ThrowOnError extends boolean = true>(options?: Options<GetPageDataData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetPageDataResponse, unknown, ThrowOnError>({
            url: '/umbraco/sustainability/api/v1/getPageData',
            ...options
        });
    }
    
    public static savePageData<ThrowOnError extends boolean = true>(options?: Options<SavePageDataData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<SavePageDataResponse, unknown, ThrowOnError>({
            url: '/umbraco/sustainability/api/v1/savePageData',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}