// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { CheckPageData, CheckPageResponse, GetAverageDataResponse, GetOverviewDataData, GetOverviewDataResponse, GetPageDataData, GetPageDataResponse, SavePageDataData, SavePageDataResponse } from './types.gen';

export class SustainabilityService {
    /**
     * @param data The data for the request.
     * @param data.pageGuid
     * @returns unknown OK
     * @throws ApiError
     */
    public static checkPage(data: CheckPageData = {}): CancelablePromise<CheckPageResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/sustainability/api/v1/checkPage',
            query: {
                pageGuid: data.pageGuid
            }
        });
    }
    
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getAverageData(): CancelablePromise<GetAverageDataResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/sustainability/api/v1/getAverageData'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.pageNumber
     * @param data.pageSize
     * @param data.orderBy
     * @param data.direction
     * @returns unknown OK
     * @throws ApiError
     */
    public static getOverviewData(data: GetOverviewDataData = {}): CancelablePromise<GetOverviewDataResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/sustainability/api/v1/getOverviewData',
            query: {
                pageNumber: data.pageNumber,
                pageSize: data.pageSize,
                orderBy: data.orderBy,
                direction: data.direction
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.pageGuid
     * @returns unknown OK
     * @throws ApiError
     */
    public static getPageData(data: GetPageDataData = {}): CancelablePromise<GetPageDataResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/sustainability/api/v1/getPageData',
            query: {
                pageGuid: data.pageGuid
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.pageGuid
     * @param data.requestBody
     * @returns boolean OK
     * @throws ApiError
     */
    public static savePageData(data: SavePageDataData = {}): CancelablePromise<SavePageDataResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/umbraco/sustainability/api/v1/savePageData',
            query: {
                pageGuid: data.pageGuid
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
}