// This file is auto-generated by @hey-api/openapi-ts

export type AveragePageMetrics = {
    carbonRating?: string | null;
    pageSize?: number | null;
    emissions?: number | null;
};

export enum DirectionModel {
    ASCENDING = 'Ascending',
    DESCENDING = 'Descending'
}

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type ExternalResource = {
    url?: string | null;
    size?: number | null;
};

export type ExternalResourceGroup = {
    type: ResourceGroupType;
    name?: string | null;
    totalSize: number;
    resources?: Array<(ExternalResource)> | null;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PageMetric = {
    id: number;
    nodeKey?: string | null;
    nodeName?: string | null;
    requestedBy?: string | null;
    requestDate: string;
    totalSize: number;
    totalEmissions: number;
    carbonRating?: string | null;
    pageData?: string | null;
    pageDataObject?: SustainabilityResponse | null;
};

export type PagedResultPageMetricModel = {
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
    totalItems: number;
    items?: Array<(PageMetric)> | null;
};

export enum ResourceGroupType {
    IMAGES = 'Images',
    SCRIPTS = 'Scripts',
    LINKS = 'Links',
    CSS = 'Css',
    OTHER = 'Other'
}

export type SustainabilityResponse = {
    lastRunDate: string;
    totalSize: number;
    totalEmissions: number;
    carbonRating?: string | null;
    resourceGroups?: Array<(ExternalResourceGroup)> | null;
};

export type CheckPageData = {
    pageGuid?: string;
};

export type CheckPageResponse = SustainabilityResponse;

export type GetAverageDataResponse = AveragePageMetrics;

export type GetOverviewDataData = {
    direction?: DirectionModel;
    orderBy?: string;
    pageNumber?: number;
    pageSize?: number;
};

export type GetOverviewDataResponse = PagedResultPageMetricModel;

export type GetPageDataData = {
    pageGuid?: string;
};

export type GetPageDataResponse = SustainabilityResponse;

export type SavePageDataData = {
    pageGuid?: string;
    requestBody?: SustainabilityResponse;
};

export type SavePageDataResponse = boolean;

export type $OpenApiTs = {
    '/umbraco/sustainability/api/v1/checkPage': {
        get: {
            req: CheckPageData;
            res: {
                /**
                 * OK
                 */
                200: SustainabilityResponse;
            };
        };
    };
    '/umbraco/sustainability/api/v1/getAverageData': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: AveragePageMetrics;
            };
        };
    };
    '/umbraco/sustainability/api/v1/getOverviewData': {
        get: {
            req: GetOverviewDataData;
            res: {
                /**
                 * OK
                 */
                200: PagedResultPageMetricModel;
            };
        };
    };
    '/umbraco/sustainability/api/v1/getPageData': {
        get: {
            req: GetPageDataData;
            res: {
                /**
                 * OK
                 */
                200: SustainabilityResponse;
            };
        };
    };
    '/umbraco/sustainability/api/v1/savePageData': {
        post: {
            req: SavePageDataData;
            res: {
                /**
                 * OK
                 */
                200: boolean;
            };
        };
    };
};