// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:50172' | (string & {});
};

export type AveragePageMetrics = {
    carbonRating?: string | null;
    pageSize?: number | null;
    emissions?: number | null;
};

export const DirectionModel = {
    ASCENDING: 'Ascending',
    DESCENDING: 'Descending'
} as const;

export type DirectionModel = typeof DirectionModel[keyof typeof DirectionModel];

export const EventMessageTypeModel = {
    DEFAULT: 'Default',
    INFO: 'Info',
    ERROR: 'Error',
    SUCCESS: 'Success',
    WARNING: 'Warning'
} as const;

export type EventMessageTypeModel = typeof EventMessageTypeModel[keyof typeof EventMessageTypeModel];

export type ExternalResource = {
    url?: string | null;
    size?: number | null;
};

export type ExternalResourceGroup = {
    type: ResourceGroupType;
    name?: string | null;
    totalSize: number;
    resources?: Array<ExternalResource> | null;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PageMetric = {
    id: number;
    nodeKey?: string | null;
    nodeName?: string | null;
    requestedBy?: string | null;
    requestDate: string;
    totalSize: number;
    totalEmissions: number;
    carbonRating?: string | null;
    pageData?: string | null;
    pageDataObject?: SustainabilityResponse | null;
};

export type PagedPageMetricModel = {
    total: number;
    items: Array<PageMetric>;
};

export const ResourceGroupType = {
    IMAGES: 'Images',
    SCRIPTS: 'Scripts',
    LINKS: 'Links',
    CSS: 'Css',
    OTHER: 'Other'
} as const;

export type ResourceGroupType = typeof ResourceGroupType[keyof typeof ResourceGroupType];

export type SustainabilityResponse = {
    lastRunDate: string;
    totalSize: number;
    totalEmissions: number;
    carbonRating?: string | null;
    resourceGroups?: Array<ExternalResourceGroup> | null;
};

export type CheckPageData = {
    body?: never;
    path?: never;
    query?: {
        pageGuid?: string;
    };
    url: '/umbraco/sustainability/api/v1/checkPage';
};

export type CheckPageResponses = {
    /**
     * OK
     */
    200: SustainabilityResponse;
};

export type CheckPageResponse = CheckPageResponses[keyof CheckPageResponses];

export type GetAverageDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/sustainability/api/v1/getAverageData';
};

export type GetAverageDataResponses = {
    /**
     * OK
     */
    200: AveragePageMetrics;
};

export type GetAverageDataResponse = GetAverageDataResponses[keyof GetAverageDataResponses];

export type GetOverviewDataData = {
    body?: never;
    path?: never;
    query?: {
        pageNumber?: number;
        pageSize?: number;
        orderBy?: string;
        direction?: DirectionModel;
    };
    url: '/umbraco/sustainability/api/v1/getOverviewData';
};

export type GetOverviewDataResponses = {
    /**
     * OK
     */
    200: PagedPageMetricModel;
};

export type GetOverviewDataResponse = GetOverviewDataResponses[keyof GetOverviewDataResponses];

export type GetPageDataData = {
    body?: never;
    path?: never;
    query?: {
        pageGuid?: string;
    };
    url: '/umbraco/sustainability/api/v1/getPageData';
};

export type GetPageDataResponses = {
    /**
     * OK
     */
    200: SustainabilityResponse;
};

export type GetPageDataResponse = GetPageDataResponses[keyof GetPageDataResponses];

export type SavePageDataData = {
    body?: SustainabilityResponse;
    path?: never;
    query?: {
        pageGuid?: string;
    };
    url: '/umbraco/sustainability/api/v1/savePageData';
};

export type SavePageDataResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type SavePageDataResponse = SavePageDataResponses[keyof SavePageDataResponses];
