// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:50172/' | (string & {});
};

export type AveragePageMetrics = {
    carbonRating?: null | string;
    pageSize?: null | number;
    emissions?: null | number;
};

export enum DirectionModel {
    ASCENDING = 'Ascending',
    DESCENDING = 'Descending'
}

export type ExternalResource = {
    url?: null | string;
    size?: null | number;
};

export type ExternalResourceGroup = {
    type: ResourceGroupType;
    name?: null | string;
    totalSize: number;
    resources?: null | Array<ExternalResource>;
};

export type PagedPageMetricModel = {
    total: number;
    items: Array<PageMetric>;
};

export type PageMetric = {
    id: number;
    nodeKey?: null | string;
    nodeName?: null | string;
    requestedBy?: null | string;
    requestDate: string;
    totalSize: number;
    totalEmissions: number;
    carbonRating?: null | string;
    pageData?: null | string;
    pageDataObject?: null | SustainabilityResponse;
};

export enum ResourceGroupType {
    IMAGES = 'Images',
    SCRIPTS = 'Scripts',
    LINKS = 'Links',
    CSS = 'Css',
    OTHER = 'Other'
}

export type SustainabilityResponse = {
    lastRunDate: string;
    totalSize: number;
    totalEmissions: number;
    carbonRating?: null | string;
    resourceGroups?: null | Array<ExternalResourceGroup>;
};

export type GetCheckPageData = {
    body?: never;
    path?: never;
    query?: {
        pageGuid?: string;
    };
    url: '/umbraco/sustainability/api/v1/checkPage';
};

export type GetCheckPageErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCheckPageResponses = {
    /**
     * OK
     */
    200: SustainabilityResponse;
};

export type GetCheckPageResponse = GetCheckPageResponses[keyof GetCheckPageResponses];

export type GetAverageDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/sustainability/api/v1/getAverageData';
};

export type GetAverageDataErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAverageDataResponses = {
    /**
     * OK
     */
    200: AveragePageMetrics;
};

export type GetAverageDataResponse = GetAverageDataResponses[keyof GetAverageDataResponses];

export type GetOverviewDataData = {
    body?: never;
    path?: never;
    query?: {
        pageNumber?: number;
        pageSize?: number;
        orderBy?: string;
        direction?: DirectionModel;
    };
    url: '/umbraco/sustainability/api/v1/getOverviewData';
};

export type GetOverviewDataErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetOverviewDataResponses = {
    /**
     * OK
     */
    200: PagedPageMetricModel;
};

export type GetOverviewDataResponse = GetOverviewDataResponses[keyof GetOverviewDataResponses];

export type GetPageDataData = {
    body?: never;
    path?: never;
    query?: {
        pageGuid?: string;
    };
    url: '/umbraco/sustainability/api/v1/getPageData';
};

export type GetPageDataErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetPageDataResponses = {
    /**
     * OK
     */
    200: SustainabilityResponse;
};

export type GetPageDataResponse = GetPageDataResponses[keyof GetPageDataResponses];

export type PostSavePageDataData = {
    body: SustainabilityResponse;
    path?: never;
    query?: {
        pageGuid?: string;
    };
    url: '/umbraco/sustainability/api/v1/savePageData';
};

export type PostSavePageDataErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostSavePageDataResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type PostSavePageDataResponse = PostSavePageDataResponses[keyof PostSavePageDataResponses];
