// This file is auto-generated by @hey-api/openapi-ts


import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './types.gen';

export class SustainabilityService {
    /**
 * @returns unknown OK
 * @throws ApiError
 */
    public static checkPage(data: $OpenApiTs['/umbraco/sustainability/api/v1/checkPage']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/sustainability/api/v1/checkPage']['get']['res'][200]> {
        const { pageGuid } = data;
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/sustainability/api/v1/checkPage',
    query: {
        pageGuid
    }
});
    }
    
    /**
 * @returns unknown OK
 * @throws ApiError
 */
    public static getAverageData(): CancelablePromise<$OpenApiTs['/umbraco/sustainability/api/v1/getAverageData']['get']['res'][200]> {
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/sustainability/api/v1/getAverageData'
});
    }
    
    /**
 * @returns unknown OK
 * @throws ApiError
 */
    public static getOverviewData(data: $OpenApiTs['/umbraco/sustainability/api/v1/getOverviewData']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/sustainability/api/v1/getOverviewData']['get']['res'][200]> {
        const { pageNumber, pageSize, orderBy, direction } = data;
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/sustainability/api/v1/getOverviewData',
    query: {
        pageNumber,
        pageSize,
        orderBy,
        direction
    }
});
    }
    
    /**
 * @returns unknown OK
 * @throws ApiError
 */
    public static getPageData(data: $OpenApiTs['/umbraco/sustainability/api/v1/getPageData']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/sustainability/api/v1/getPageData']['get']['res'][200]> {
        const { pageGuid } = data;
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/sustainability/api/v1/getPageData',
    query: {
        pageGuid
    }
});
    }
    
    /**
 * @returns boolean OK
 * @throws ApiError
 */
    public static savePageData(data: $OpenApiTs['/umbraco/sustainability/api/v1/savePageData']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/sustainability/api/v1/savePageData']['post']['res'][200]> {
        const { pageGuid, requestBody } = data;
        return __request(OpenAPI, {
    method: 'POST',
    url: '/umbraco/sustainability/api/v1/savePageData',
    query: {
        pageGuid
    },
    body: requestBody,
    mediaType: 'application/json'
});
    }
    
}