// This file is auto-generated by @hey-api/openapi-ts


export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type ExternalResource = {
    url?: string | null;
    size: number;
};

export type ExternalResourceGroup = {
    type: ResourceGroupType;
    name?: string | null;
    totalSize: number;
    resources?: Array<(ExternalResource)> | null;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ResourceGroupType = 'Images' | 'Scripts' | 'Styles' | 'Other';

export type SustainabilityResponse = {
    lastRunDate: string;
    totalSize: number;
    totalEmissions: number;
    carbonRating?: string | null;
    resourceGroups?: Array<(ExternalResourceGroup)> | null;
};

export type $OpenApiTs = {
    '/umbraco/sustainability/api/v1/checkPage': {
        get: {
            req: {
                pageGuid?: string;
            };
            res: {
                /**
 * Success
 */
                200: SustainabilityResponse;
            };
        };
    };
    '/umbraco/sustainability/api/v1/getPageData': {
        get: {
            req: {
                pageGuid?: string;
            };
            res: {
                /**
 * Success
 */
                200: SustainabilityResponse;
            };
        };
    };
    '/umbraco/sustainability/api/v1/savePageData': {
        post: {
            req: {
                pageGuid?: string;
                requestBody?: SustainabilityResponse;
            };
            res: {
                /**
 * Success
 */
                200: boolean;
            };
        };
    };
};