/* tslint:disable */
/* eslint-disable */
/**
 * Sustainability API
 * Umbraco.Community.Sustainability
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ExternalResource } from './ExternalResource';
import {
    instanceOfExternalResource,
    ExternalResourceFromJSON,
    ExternalResourceFromJSONTyped,
    ExternalResourceToJSON,
} from './ExternalResource';

/**
 * @type ExternalResourceGroupResourcesInner
 * 
 * @export
 */
export type ExternalResourceGroupResourcesInner = ExternalResource;

export function ExternalResourceGroupResourcesInnerFromJSON(json: any): ExternalResourceGroupResourcesInner {
    return ExternalResourceGroupResourcesInnerFromJSONTyped(json, false);
}

export function ExternalResourceGroupResourcesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalResourceGroupResourcesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ExternalResourceFromJSONTyped(json, true) };
}

export function ExternalResourceGroupResourcesInnerToJSON(value?: ExternalResourceGroupResourcesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfExternalResource(value)) {
        return ExternalResourceToJSON(value as ExternalResource);
    }

    return {};
}

