/* tslint:disable */
/* eslint-disable */
/**
 * Sustainability API
 * Umbraco.Community.Sustainability
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExternalResource
 */
export interface ExternalResource {
    /**
     * 
     * @type {string}
     * @memberof ExternalResource
     */
    url?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ExternalResource
     */
    size: number;
}

/**
 * Check if a given object implements the ExternalResource interface.
 */
export function instanceOfExternalResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "size" in value;

    return isInstance;
}

export function ExternalResourceFromJSON(json: any): ExternalResource {
    return ExternalResourceFromJSONTyped(json, false);
}

export function ExternalResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'size': json['size'],
    };
}

export function ExternalResourceToJSON(value?: ExternalResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'size': value.size,
    };
}

