/* tslint:disable */
/* eslint-disable */
/**
 * Sustainability API
 * Umbraco.Community.Sustainability
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ExternalResourceGroup } from './ExternalResourceGroup';
import {
    instanceOfExternalResourceGroup,
    ExternalResourceGroupFromJSON,
    ExternalResourceGroupFromJSONTyped,
    ExternalResourceGroupToJSON,
} from './ExternalResourceGroup';

/**
 * @type SustainabilityResponseResourceGroupsInner
 * 
 * @export
 */
export type SustainabilityResponseResourceGroupsInner = ExternalResourceGroup;

export function SustainabilityResponseResourceGroupsInnerFromJSON(json: any): SustainabilityResponseResourceGroupsInner {
    return SustainabilityResponseResourceGroupsInnerFromJSONTyped(json, false);
}

export function SustainabilityResponseResourceGroupsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SustainabilityResponseResourceGroupsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ExternalResourceGroupFromJSONTyped(json, true) };
}

export function SustainabilityResponseResourceGroupsInnerToJSON(value?: SustainabilityResponseResourceGroupsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfExternalResourceGroup(value)) {
        return ExternalResourceGroupToJSON(value as ExternalResourceGroup);
    }

    return {};
}

