/* tslint:disable */
/* eslint-disable */
/**
 * Sustainability API
 * Umbraco.Community.Sustainability
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SustainabilityResponse } from './SustainabilityResponse';
import {
    instanceOfSustainabilityResponse,
    SustainabilityResponseFromJSON,
    SustainabilityResponseFromJSONTyped,
    SustainabilityResponseToJSON,
} from './SustainabilityResponse';

/**
 * @type UmbracoSustainabilityApiV1SavePageDataPostRequest
 * 
 * @export
 */
export type UmbracoSustainabilityApiV1SavePageDataPostRequest = SustainabilityResponse;

export function UmbracoSustainabilityApiV1SavePageDataPostRequestFromJSON(json: any): UmbracoSustainabilityApiV1SavePageDataPostRequest {
    return UmbracoSustainabilityApiV1SavePageDataPostRequestFromJSONTyped(json, false);
}

export function UmbracoSustainabilityApiV1SavePageDataPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UmbracoSustainabilityApiV1SavePageDataPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...SustainabilityResponseFromJSONTyped(json, true) };
}

export function UmbracoSustainabilityApiV1SavePageDataPostRequestToJSON(value?: UmbracoSustainabilityApiV1SavePageDataPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfSustainabilityResponse(value)) {
        return SustainabilityResponseToJSON(value as SustainabilityResponse);
    }

    return {};
}

